export const AUDIT_ACCOUNT_VERIFICATION_REQUEST = "AUDIT_ACCOUNT_VERIFICATION_REQUEST";
export const AUDIT_ACCOUNT_VERIFICATION_SUCCESS = "AUDIT_ACCOUNT_VERIFICATION_SUCCESS";
export const AUDIT_ACCOUNT_VERIFICATION_FAIL = "AUDIT_ACCOUNT_VERIFICATION_FAIL";

export const AUDIT_ACTIVITY_STATUS_VERIFICATION_REQUEST = "AUDIT_ACTIVITY_STATUS_VERIFICATION_REQUEST";
export const AUDIT_ACTIVITY_STATUS_VERIFICATION_SUCCESS = "AUDIT_ACTIVITY_STATUS_VERIFICATION_SUCCESS";
export const AUDIT_ACTIVITY_STATUS_VERIFICATION_FAIL = "AUDIT_ACTIVITY_STATUS_VERIFICATION_FAIL";

export const AUDIT_CENSORED_DETECTION_REQUEST = "AUDIT_CENSORED_DETECTION_REQUEST";
export const AUDIT_CENSORED_DETECTION_SUCCESS = "AUDIT_CENSORED_DETECTION_SUCCESS";
export const AUDIT_CENSORED_DETECTION_FAIL = "AUDIT_CENSORED_DETECTION_FAIL";